# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IFB299Project', '0002_pageee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placeinformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Placename', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=400)),
                ('long', models.CharField(max_length=15)),
                ('lat', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='pageee',
            name='category',
        ),
        migrations.DeleteModel(
            name='Pageee',
        ),
    ]
