# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('IFB299Project', '0003_auto_20171004_0548'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=300)),
                ('Username', models.CharField(max_length=400)),
                ('name', models.CharField(max_length=30)),
                ('typwOfUser', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='placeinformation',
            name='typeOfPlace',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
