# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IFB299Project', '0006_auto_20171024_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
        migrations.AddField(
            model_name='users',
            name='PASSWO',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
    ]
